# Taken and modified from https://github.com/BurntSushi/ripgrep/blob/895e26a000cc54643691bdaef5fd7ea5f4451a89/appveyor.yml

cache:
  - c:\cargo\registry
  - c:\cargo\git

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\twitchchat

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\twitchchat\\target"
  global:
    PROJECT_NAME: twitchchat
    RUST_BACKTRACE: full
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BITS: "64"
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      BITS: "64"
      MSYS2: "1"

matrix:
  fast_finish: true

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc --version
  - cargo --version
  - rustup --version

build: "off"

# Equivalent to Travis' `script` phase
test_script:
  - cargo test --verbose --all

branches:
  only:
    - /^\d+\.\d+\.\d+$/
    - master
    - dev
